---
- name: Setup OCI Distribution
  hosts: cluster

  tasks:
    - name: Create Cloudflare API token secret
      kubernetes.core.k8s:
        name: cloudflare-api-token
        namespace: cert-manager
        definition:
          kind: Secret
          type: Opaque
          data:
            api-token: "{{ cloudflare_api_token | b64encode }}"

    - name: Create Cluster Issuer
      kubernetes.core.k8s:
        definition: "{{ lookup('file', '../resources/cluster-issuer.yaml') }}"
