---
- name: Setup Gateway
  hosts: cluster

  tasks:
    - name: Create Istio Gateway namespace
      kubernetes.core.k8s:
        name: istio-gateway
        kind: Namespace

    - name: Create Cloudflare API token secret
      kubernetes.core.k8s:
        name: cloudflare-api-token
        namespace: istio-gateway
        definition:
          kind: Secret
          type: Opaque
          data:
            api-token: "{{ cloudflare_api_token | b64encode }}"

    - name: Create Issuer
      kubernetes.core.k8s:
        namespace: istio-gateway
        definition: "{{ lookup('file', '../resources/issuer.yaml') }}"

    - name: Create Certificate
      kubernetes.core.k8s:
        namespace: istio-gateway
        definition: "{{ lookup('file', '../resources/certificate.yaml') }}"

    - name: Install Istio Gateway
      kubernetes.core.helm:
        name: istio-gateway
        namespace: istio-gateway
        chart_ref: gateway
        chart_repo_url: https://istio-release.storage.googleapis.com/charts
        atomic: true
        wait: true
        values: "{{ lookup('file', '../resources/values/istio-gateway.yaml') | from_yaml }}"

    - name: Create Gateway
      kubernetes.core.k8s:
        namespace: istio-gateway
        definition: "{{ lookup('file', '../resources/gateway.yaml') }}"
