---
- name: Setup Istio
  hosts: cluster

  tasks:
    - name: Install Gateway API Resources
      kubernetes.core.k8s:
        definition: "{{ lookup('kubernetes.core.kustomize', dir='https://github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.2.0') }}"

    - name: Create Istio namespace
      kubernetes.core.k8s:
        name: istio-system
        kind: Namespace

    - name: Install Istio Base
      kubernetes.core.helm:
        name: istio-base
        namespace: istio-system
        chart_ref: base
        chart_repo_url: https://istio-release.storage.googleapis.com/charts
        atomic: true
        wait: true
        values: "{{ lookup('file', '../resources/values/istio-base.yaml') | from_yaml }}"

    - name: Install Istio Istiod
      kubernetes.core.helm:
        name: istio-istiod
        namespace: istio-system
        chart_ref: istiod
        chart_repo_url: https://istio-release.storage.googleapis.com/charts
        atomic: true
        wait: true
        values: "{{ lookup('file', '../resources/values/istio-istiod.yaml') | from_yaml }}"

    - name: Create Istio Gateway namespace
      kubernetes.core.k8s:
        name: istio-gateway
        kind: Namespace

    - name: Install Istio Gateway
      kubernetes.core.helm:
        name: istio-gateway
        namespace: istio-gateway
        chart_ref: gateway
        chart_repo_url: https://istio-release.storage.googleapis.com/charts
        atomic: true
        wait: true
        values: "{{ lookup('file', '../resources/values/istio-gateway.yaml') | from_yaml }}"
