all:
  hosts:
    cluster:
      ansible_host: 10.4.4.125
    node1:
      ansible_host: 10.4.4.111
      ip: 10.4.4.111
      access_ip: 10.4.4.111
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
