---
- name: Install Cert Manager
  ansible.builtin.import_playbook: playbooks/cert-manager.yaml

- name: Install TopoLVM
  ansible.builtin.import_playbook: playbooks/topolvm.yaml

- name: Install NGINX Gateway Fabric
  ansible.builtin.import_playbook: playbooks/gateway.yaml
